let NUMEROS=[1,2,3]
console.log((NUMEROS[0]+NUMEROS[1]+NUMEROS[2])/NUMEROS.length)
// ojo de el lenght
// A LA PROXIMA, HACER TODO EN VARIABLES Y ADMINISTRALO EN SUMA, PROMEDIO Y ESIDUAL. PERO BUEN CAMINO